plugins {
	id 'java'
	id 'org.springframework.boot' version '3.4.3'
	id 'io.spring.dependency-management' version '1.1.7'
}



group = 'com.chase'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	
	// https://mvnrepository.com/artifact/com.oracle.oci.sdk/oci-java-sdk-objectstorage
	//implementation 'com.oracle.oci.sdk:oci-java-sdk-objectstorage:3.61.0'
	
	implementation 'com.oracle.oci.sdk:oci-java-sdk-objectstorage:3.61.0'
	implementation 'com.oracle.oci.sdk:oci-java-sdk-common-httpclient-jersey3:3.61.0'
	// https://mvnrepository.com/artifact/com.oracle.database.jdbc/ojdbc11
	//implementation 'com.oracle.oci.sdk:oci-java-sdk-common:3.61.0'
	
	//implementation 'com.oracle.oci.sdk:oci-java-sdk-common-httpclient-apache:3.61.0'
	//implementation 'com.oracle.oci.sdk:oci-java-sdk-common-httpclient-jersey:3.61.0'
	// https://mvnrepository.com/artifact/com.oracle.oci.sdk/oci-java-sdk-common-httpclient-jersey3
	
	
	// Jersey Dependencies (Compatible with OCI SDK v3.61.0)
    //implementation 'org.glassfish.jersey.core:jersey-client:3.1.2'
    //implementation 'org.glassfish.jersey.inject:jersey-hk2:3.1.2'
    
    //implementation 'jakarta.ws.rs:jakarta.ws.rs-api:3.1.0'
    
    //implementation 'org.glassfish.jersey.connectors:jersey-apache-connector:3.1.2' 
    //implementation 'org.glassfish.jersey.core:jersey-common:3.1.2' 
	
	//implementation 'org.glassfish.jersey.core:jersey-client:2.39'
    //implementation 'org.glassfish.jersey.inject:jersey-hk2:2.39'
	
	implementation 'org.thymeleaf.extras:thymeleaf-extras-springsecurity6'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	// https://mvnrepository.com/artifact/org.mockito/mockito-junit-jupiter
    testImplementation("org.mockito:mockito-junit-jupiter:5.16.1")
	runtimeOnly 'com.h2database:h2'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.security:spring-security-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	
	implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'
    
    /*configurations.all {
        exclude group: "javax.ws.rs", module: "javax.ws.rs-api"
        exclude group: "org.glassfish.jersey.core", module: "jersey-client"
        exclude group: "org.glassfish.jersey.inject", module: "jersey-hk2"
    }*/
    
    
}

tasks.named("processResources") {
    exclude("index/**")
}

task unittest(type: Test) {
    testLogging {
        events "PASSED", "FAILED", "SKIPPED"
    }
    systemProperty 'spring.profiles.active', 'unit-test'
    useJUnitPlatform()
}

task inttest(type: Test) {
    testLogging {
        events "PASSED", "FAILED", "SKIPPED"
    }
    systemProperty 'spring.profiles.active', 'int-test'
    useJUnitPlatform()
}

test {
    testLogging {
        events "PASSED", "FAILED", "SKIPPED"
    }
    systemProperty 'spring.profiles.active', 'test'
    useJUnitPlatform()
    
}
