spring.application.name=portfolio
server.port=80
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.profiles.active=dev
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.resource=TRACE
#Remember to change this out when launching
# Disable Spring Security's default login form
#spring.security.user.name=admin
#spring.security.user.password=admin
server.error.include-message=always

#spring.web.resources.static-locations=classpath:/static/
management.endpoints.web.exposure.include=*
management.endpoint.mappings.enabled=true
#management.endpoints.web.exposure.include=*
#management.endpoint.mappings.enabled=true


#spring.datasource.url=jdbc:sqlite:database/users.db
#spring.datasource.driver-class-name=org.sqlite.JDBC
#spring.datasource.username= # SQLite does not require a username
#spring.datasource.password= # SQLite does not require a password

