spring.application.name=portfolio
server.port=443
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.resource=TRACE
server.error.include-message=always
management.endpoints.web.exposure.include=*
management.endpoint.mappings.enabled=true
server.ssl.enabled=true
server.ssl.protocol=TLS
server.port=443
logging.level.org.apache.tomcat.util.net=DEBUG


